# Use the official Node.js image based on Alpine Linux
FROM node:18.17-alpine3.18

# Set the working directory
WORKDIR /app/frontend

# Copy application files
COPY . .

# Install dependencies
RUN npm install

# Expose the port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
